---
title: "Chart review results"
author: "Anthony Staines"
date: "`r Sys.Date()`"
output:
  pdf_document: 
    toc: true
    fig_caption: true
    number_sections: true
    latex_engine: xelatex
  word_document: default
  html_document: default
editor_options:
  chunk_output_type: console
bibliography: references.bib
csl: vancouver.csl
---
# Setup

```{r setup, include=FALSE}
rm(list=ls())

library(tidyverse)
library(knitr)
library(kableExtra)
knitr::opts_chunk$set(echo = TRUE)
```

# Load the chart review data

Load the data, select key variables, and shift to long form.

```{r Load data}

Cost2Care.HIPE <- readRDS(file = "data/Cost2Care.HIPE.Rds") %>%
    select(StudyID, PN, UTI, PU, DL, F2M) %>%
    pivot_longer(!StudyID, names_to = "Outcome",
                 values_to = "Count") %>%
    mutate(Count = case_match(Count, # Numeric version of Count
                              "No"  ~ 0,
                              "Yes" ~1))

```

Prepare a dataframe with Source, Cases, Total, Estimate

```{r}
Source = "Chart_review"

Chart <- Cost2Care.HIPE %>%
    mutate(Source = Source) %>%
    relocate(Source) %>%
    group_by(Source,Outcome) %>%
    summarise(Cases = sum(Count),
              Total = n(),
              .groups = "drop") %>%
    mutate(Estimate = Cases/Total)
```

Calculate confidence intervals for the point estimate of the prevalence of adverse events of each type.

```{r calculate CI}
CI <- Hmisc::binconf(Chart$Cases, Chart$Total, include.x = TRUE, include.n = TRUE) # Calculate default Wilson CI's - A. Agresti and B.A. Coull, Approximate is better than "exact" for interval estimation of binomial proportions, American Statistician, 52:119–126, 1998.

Chart <- Chart %>%
  cbind(as_tibble(CI)) %>%
  select(!(X:PointEst)) #Glue the CI's into the tibble

# Sort out nicely ordered factor levels for chart labels
Chart <- Chart %>%
  mutate(Outcome = 
           fct_relevel(Outcome,
                  "PN", "UTI", "PU", "DL", "F2M") ) %>%
  mutate(Outcomes = case_match(Outcome,
                      "PN" ~ "Pneumonia",
                      "UTI" ~ "UTI",
                      "PU" ~  "Pressure Ulcer",
                      "DL" ~  "Delirium",
                      "F2M" ~ "Failure to Maintain")) %>%
  mutate(Outcomes = 
           fct_relevel(Outcomes,
                  "Pneumonia", "UTI",
                  "Pressure Ulcer", "Delirium",
                  "Failure to Maintain") )
```

```{r Point estimates and 95% confidence intervals for each outcome in the chart review data, fig.cap= 'Point estimates and 95% confidence intervals for each outcome in the chart review data.', fig.dpi=1200, fig.height=5, fig.width=7}

ggplot(data=Chart, aes(x = Outcomes, y = Estimate)) +
  geom_point(colour = 'red', size = 4) +
  geom_errorbar(aes(ymin = Lower, ymax = Upper, width = 0.2)) +
  labs(title = "Point estimates and 95% CI for outcomes",
       subtitle = "People 65 + discharged from study hospital") +
  guides(colour = "none", fill = "none", size = "none") +
    theme_minimal(base_size = 12)

```

#Prediction intervals

```{r Prediction intervals}
library(extraDistr)

PI <- function(Study_Population, Study_Events,
               Event_Names,
               Prediction_Population,
               alpha  = 1, beta = 1,
               lower.tail = TRUE)
{  
  JVEC  <- rep( seq( from = 0,
          to = Prediction_Population-1,
          by = 1),
          times = length(Study_Events))
  
  NAMES <- rep(Event_Names,
               times = length(JVEC) /
                 length(Event_Names ))

  PROBS <- pbbinom(q = JVEC,
                   size = Study_Population,
                   alpha = (alpha + Study_Events),
                   beta = (beta + Study_Population - k),
                   lower.tail = lower.tail)

#cat(length(JVEC),length(CASE_NUMBERS),length(NAMES),length(PROBS),"\n")

glimpse(tibble(JVEC, Event_Names))

Result <- tibble(JVEC, NAMES, PROBS) %>%
  select(NAMES, JVEC, PROBS) %>%
  arrange(NAMES,JVEC,PROBS)

return((Result))
  
#Probs_min = max(which(Probs <= 0.025))
#  Probs_max = min(which(Probs >= 0.975))

}


#function(Study_Population, Study_Events,
#               Event_Names,
#               Prediction_Population,
#               alpha  = 1, beta = 1,
#               lower.tail = TRUE)

Probs2 <- PI(Study_Population = 1000,
             Study_Events = Chart$Cases,
             Event_Names = Chart$Outcomes,
             Prediction_Population = 1000,
             alpha = 1, beta = 1,
             lower.tail = TRUE)
Probs2 <- PI(1000,Chart$Cases,1000,1,1,"upper")


Chart <- Chart %>%
  mutate(m = Total) %>%
  mutate(alpha = 1) %>%
  mutate(beta = 1) %>%
  mutate(PEstimate = m * (alpha + Cases)/(alpha + beta + Total)) # Sanity check - very very close to frequentist estimate as expected

Chart2 <- Chart %>%
  mutate(Plower =  PI(n = 1000,
                      k =Cases, m=1000,
                      alpha = 1, beta = 1,
                      type = "lower")) %>%
  mutate(Pupper =  PI(n = 1000,
                      k =Cases, m=1000,
                      alpha = 1, beta = 1,
                      type = "lower")) 
  

Probs <- pbbinom(seq(0, m-1, by = 1),
                 size = m, alpha = (alpha + 100),
                 beta = (beta + n - 100))
min(which(Probs >= 0.975))
max(which(Probs <= 0.025))

```
