---
title: "HIPE Outcomes"
author: "AS"
date: "`r Sys.Date()`"
output:
  html_document: default
  word_document: default
  pdf_document: 
    toc: true
    fig_caption: true
    number_sections: true
    latex_engine: xelatex
editor_options:
  chunk_output_type: console
bibliography: references.bib
csl: vancouver.csl
---

```{r setup, include=FALSE}
rm(list=ls())
library(tidyverse)
library(lme4)
library(broom)
library(broom.mixed)
library(gtsummary)
library(sjPlot)
library(patchwork)

#tidymodels_prefer(quiet = TRUE)

knitr::opts_chunk$set(echo = FALSE, cache = TRUE,
                      warning = NA, message = NA,
                      fig.pos = 'H',
                      cache.extra = knitr::rand_seed)

#How many CPUs?
N = parallel:::detectCores()

  options(Ncpus = N)
  options(mc.cores = N)

options(dplyr.summarise.inform = FALSE, # shut up summarise
        ranger.num.threads = N) # Prepare for rf models

set.seed(979)
rm(N)
```


# Aims

To examine mixed models of the main outcomes in HIPE - Length of stay,a nd Death in hospital

# Load data

First, we loads the main HIPE data, and removes data and factor levels for maternity and specialist hospitals.

```{r Load the HIPE data}

#####################################################
# Load the corresponding HIPE data
# 
HIPE <- readRDS('data/HIPE.Rds')
table(HIPE$ModelF)
```


# LMER models

```{r lmer1}
Model0 <- lm(data=HIPE,
             rawlos ~ age + sex + ScoreEl + Source + SeasonOfAdmission)

Model1 <- lmer(data=HIPE,
             rawlos ~ age + sex + ScoreEl + Source + SeasonOfAdmission +
               (1 | ModelF) )

Model2 <- lmer(data=HIPE,
             rawlos ~ age + sex + ScoreEl + Source + SeasonOfAdmission + ModelF +
               (1 | HospCode))

Model3 <- lmer(data=HIPE,
             rawlos ~ age + sex + ScoreEl + Source + SeasonOfAdmission +
               (1 | ModelF/HospCode))


summary(Model0)
summary(Model1)
summary(Model2)
summary(Model3)

AIC(Model0); AIC(Model1); AIC(Model2); AIC(Model3)
P0 <-  plot_model(Model0, title = 'Model0')
P1 <-  plot_model(Model1, title = 'Model1')
P2 <-  plot_model(Model2, title = 'Model2')
P3 <-  plot_model(Model3, title = 'Model3')

P0 + P1 + P2 + P3

R1 <-  plot_model(Model1, type = 're', title = 'Model1')
R2 <-  plot_model(Model2, type = "re", title = 'Model2')
R3 <-  plot_model(Model3, type = 're', title = 'Model3')

R1 + R2 + R3
```
