---
title: "Variable and model selection"
author: "Anthony Staines"
date: "`r Sys.Date()`"
output:
  pdf_document: 
    toc: true
    fig_caption: true
    number_sections: true
    latex_engine: xelatex
  word_document: default
  html_document: default
editor_options:
  chunk_output_type: console
bibliography: references.bib
csl: vancouver.csl
---


```{r Clean environment, include = FALSE}
  rm(list = ls())
```

```{r setup, include=FALSE}
library(rstanarm)
library(projpred)
library(tidyverse)

library(knitr)
library(kableExtra)

#tidymodels_prefer(quiet = TRUE)
#st_options(ctable.round.digits = 2)

#How many CPU's?
N = parallel::detectCores()
  options(Ncpus = N - 1)
  options(mc.cores = N - 1)
#  setDTthreads(threads = N - 1,
#               restore_after_fork = TRUE,
#               throttle = 1024)

options(dplyr.summarise.inform = FALSE, # shut up summarise
        ranger.num.threads = N - 1) # Prepare for rf models

knitr::opts_chunk$set(
	echo = FALSE,
	fig.pos = "H",
	message = FALSE,
	warning = FALSE,
	cache = TRUE,
	cache.extra = knitr::rand_seed,
	cache.lazy = FALSE
)
rm(N)
```

```{r Load existing data}
HIPE <- readRDS('data/HIPE.Rds')
CCH <- readRDS('data/CCH.Rds')
glimpse(CCH)

# STAN does not like character variables, so we turn them into factors (No =  0, and  Yes = 1, more or less.

CCH <- CCH |>
  mutate(across(where(is.character), ~as_factor(.)))  |>
  rowid_to_column(var = 'rowid')
glimpse(CCH)

HIPE <- HIPE |>
  mutate(across(where(is.character), ~as_factor(.))) |>
  rowid_to_column('rowid') # Add a rowid variable

glimpse(HIPE)

table(CCH$PN) # 79 positive out of 1,000
```


```{r Load tasks}
tsk_PN   <- readRDS('data/tsk.PN')
tsk_PNk  <- readRDS('data/tsk.PNk')
tsk_UTI  <- readRDS('data/tsk.UTI')
tsk_UTIk <- readRDS('data/tsk.UTIk')
tsk_PU   <- readRDS('data/tsk.PU')
tsk_PUk  <- readRDS('data/tsk.PUk')
tsk_DL   <- readRDS('data/tsk.DL')
tsk_DLk  <- readRDS('data/tsk.DLk')
tsk_F2M  <- readRDS('data/tsk.F2M')
tsk_F2Mk <- readRDS('data/tsk.F2Mk')
```

```{r Load fits}
fit_PN   <- readRDS('data/fit.PN')
fit_PNk  <- readRDS('data/fit.PNk')
fit_UTI  <- readRDS('data/fit.UTI')
fit_UTIk <- readRDS('data/fit.UTIk')
fit_PU   <- readRDS('data/fit.PU')
fit_PUk  <- readRDS('data/fit.PUk')
fit_DL   <- readRDS('data/fit.DL')
fit_DLk  <- readRDS('data/fit.DLk')
fit_F2M  <- readRDS('data/fit.F2M')
fit_F2Mk <- readRDS('data/fit.F2Mk')
```

```{r}
ref_fit_PU <- get_refmodel(fit_PU)

```

